#ifndef SENEGAL_SLEXER_H
#define SENEGAL_SLEXER_H

typedef enum _SenegalTokenType {
    // Keywords
    SENEGAL_ASYNC, SENEGAL_AWAIT, SENEGAL_BREAK, SENEGAL_CASE, SENEGAL_CLASS, SENEGAL_CONTINUE,
    SENEGAL_DEFAULT, SENEGAL_ELSE, SENEGAL_EXTENDS, SENEGAL_FALSE,
    SENEGAL_FINAL, SENEGAL_FOR, SENEGAL_FUNCTION, SENEGAL_IF, SENEGAL_IMPORT,
    SENEGAL_RETURN, SENEGAL_NULL, SENEGAL_SUPER, SENEGAL_SWITCH, SENEGAL_THIS, SENEGAL_TRUE, SENEGAL_VAR, SENEGAL_WHILE,

    SENEGAL_ID, SENEGAL_STRING, SENEGAL_NUMBER, SENEGAL_HEX,

    SENEGAL_AMP, SENEGAL_AMP_AMP, SENEGAL_BANG, SENEGAL_BANG_EQUAL, SENEGAL_EQUAL, SENEGAL_EQUAL_EQUAL, SENEGAL_EQUAL_GREATER,
    SENEGAL_GREATER, SENEGAL_GREATER_GREATER, SENEGAL_GREATER_EQUAL, SENEGAL_LESSER, SENEGAL_LESSER_LESSER,
    SENEGAL_LESSER_EQUAL, SENEGAL_PIPE, SENEGAL_PIPE_PIPE, SENEGAL_TILDE,

    SENEGAL_LPAREN, SENEGAL_RPAREN, SENEGAL_LBRACE, SENEGAL_RBRACE, SENEGAL_LBRACKET, SENEGAL_RBRACKET,

    SENEGAL_CARET, SENEGAL_COMMA, SENEGAL_COLON, SENEGAL_DOT, SENEGAL_MINUS, SENEGAL_MINUS_EQUAL,
    SENEGAL_MINUS_MINUS, SENEGAL_PLUS, SENEGAL_PLUS_EQUAL, SENEGAL_PLUS_PLUS, SENEGAL_QUESTION, SENEGAL_SEMI,
    SENEGAL_SLASH, SENEGAL_SLASH_EQUAL, SENEGAL_STAR, SENEGAL_STAR_EQUAL, SENEGAL_STAR_STAR,

    SENEGAL_ERROR, SENEGAL_EOF

} SenegalTokenType;

typedef struct {
    SenegalTokenType type;
    const char* start;
    int length;
    int line;
} Token;

typedef struct {
    char* start;
    char* current;
    int line;
} Lexer;


void initLexer(Lexer* lexer, char* source);
Token getNextToken(Lexer* lexer);

#endif //SENEGAL_SLEXER_H