#ifdef RULE

RULE(SENEGAL_AMP, NULL, parseBinary, BIT_AND)
RULE(SENEGAL_AMP_AMP, NULL, parseAnd, PREC_AND)

RULE(SENEGAL_BANG, parseUnary, NULL, NONE)
RULE(SENEGAL_BANG_EQUAL, NULL, parseBinary, EQUALITY)

RULE(SENEGAL_CASE, NULL, NULL, NONE)
RULE(SENEGAL_CARET, NULL, parseBinary, BIT_XOR)
RULE(SENEGAL_CLASS, NULL, NULL, NONE)
RULE(SENEGAL_COMMA, NULL, NULL, NONE)
RULE(SENEGAL_COLON, NULL, NULL, NONE)

RULE(SENEGAL_DEFAULT, NULL, NULL, NONE)
RULE(SENEGAL_DOT, NULL, parseDot, CALL)

RULE(SENEGAL_ELSE, NULL, NULL, NONE)
RULE(SENEGAL_ENUM, NULL, NULL, NONE)
RULE(SENEGAL_EQUAL, NULL, NULL, NONE)
RULE(SENEGAL_EQUAL_EQUAL, NULL, parseBinary, EQUALITY)
RULE(SENEGAL_ERROR, NULL, NULL, NONE)
RULE(SENEGAL_EOF, NULL, NULL, NONE)

RULE(SENEGAL_FALSE, parseLiteral, NULL, NONE)
RULE(SENEGAL_FOR, NULL, NULL, NONE)
RULE(SENEGAL_FUNCTION, parseClosure, NONE, NONE)

RULE(SENEGAL_GREATER, NULL, parseBinary, COMPARISON)
RULE(SENEGAL_GREATER_GREATER, NULL, parseBinary, BIT_SHIFT)
RULE(SENEGAL_GREATER_EQUAL, NULL, parseBinary, ASSIGNMENT)

RULE(SENEGAL_HEX, parseHex, NULL, NONE)

RULE(SENEGAL_ID, parseIdentifier, NULL, NONE)
RULE(SENEGAL_IF, NULL, NULL, NONE)

RULE(SENEGAL_LBRACE, parseMap, NULL, NONE)
RULE(SENEGAL_LBRACKET, parseList, parseAccess, CALL)
RULE(SENEGAL_LESSER, NULL, parseBinary, COMPARISON)
RULE(SENEGAL_LESSER_LESSER, NULL, parseBinary, BIT_SHIFT)
RULE(SENEGAL_LESSER_EQUAL, NULL, parseBinary, ASSIGNMENT)
RULE(SENEGAL_LPAREN, parseGroup, parseFunctionCall, CALL)

RULE(SENEGAL_MINUS, parseUnary, parseBinary, TERM)
RULE(SENEGAL_MINUS_EQUAL, NULL, NULL, TERM)
RULE(SENEGAL_MINUS_MINUS, NULL, NULL, TERM)
RULE(SENEGAL_MOD, NULL, parseBinary, FACTOR)
RULE(SENEGAL_MOD_EQUAL, NULL, NULL, FACTOR)

RULE(SENEGAL_NUMBER, parseNumber, NULL, NONE)
RULE(SENEGAL_NULL, parseLiteral, NULL, NONE)

RULE(SENEGAL_PIPE, NULL, parseBinary, BIT_OR)
RULE(SENEGAL_PIPE_PIPE, NULL, parseOr, PREC_OR)
RULE(SENEGAL_PIPELINE, NULL, parsePipeline, PREC_OR)
RULE(SENEGAL_PLUS, NULL, parseBinary, TERM)
RULE(SENEGAL_PLUS_EQUAL, NULL, NULL, TERM)
RULE(SENEGAL_PLUS_PLUS, NULL, NULL, TERM)

RULE(SENEGAL_QUESTION, NULL, parseTernary, ASSIGNMENT)

RULE(SENEGAL_RBRACE, NULL, NULL, NONE)
RULE(SENEGAL_RBRACKET, NULL, NULL, NONE)
RULE(SENEGAL_RETURN, NULL, NULL, NONE)
RULE(SENEGAL_RPAREN, NULL, NULL, NONE)

RULE(SENEGAL_SEMI, NULL, NULL, NONE)
RULE(SENEGAL_SLASH, NULL, parseBinary, FACTOR)
RULE(SENEGAL_SLASH_EQUAL, NULL, NULL, FACTOR)
RULE(SENEGAL_STAR, NULL, parseBinary, FACTOR)
RULE(SENEGAL_STAR_EQUAL, NULL, NULL, FACTOR)
RULE(SENEGAL_STAR_STAR, NULL, parseBinary, FACTOR)
RULE(SENEGAL_STATIC, NULL, NULL, NONE)
RULE(SENEGAL_STRING, parseString, NULL, NONE)
RULE(SENEGAL_SUPER, parseSuper, NULL, NONE)
RULE(SENEGAL_SUSPEND, NULL, NULL, NONE)
RULE(SENEGAL_SWITCH, NULL, NULL, NONE)

RULE(SENEGAL_THIS, parseThis, NULL, NONE)
RULE(SENEGAL_THROW, NULL, NULL, NONE)
RULE(SENEGAL_TILDE, parseUnary, NULL, UNARY)
RULE(SENEGAL_TRUE, parseLiteral, NULL, NONE)

RULE(SENEGAL_WHILE, NULL, NULL, NONE)

RULE(SENEGAL_VAR, NULL, NULL, NONE)

RULE(SENEGAL_YIELD, NULL, NULL, NONE)

#endif //SENEGAL_SRULES_H
